CC = devcontainer
NVIM_PACKAGES = nvim
UTILS_PACKAGES = utils
BASE_IMAGE = ubuntu:latest

CONTAINER_NAME = test-devcontainer

.PHONY: up test stop remove down test-nvim test-utils test-global test-autogenerated

up:
	docker run -it --name $(CONTAINER_NAME) -v .:/workspace ubuntu:latest bash

down: stop remove

remove:
	docker container rm $(CONTAINER_NAME)

stop:
	docker stop $(CONTAINER_NAME)

test-nvim:
	$(CC) features test -f $(NVIM_PACKAGES) --skip-duplicated --skip-autogenerated .

test-utils:
	$(CC) features test -f $(UTILS_PACKAGES) --skip-duplicated --skip-autogenerated .

test-global:
	$(CC) features test --global-scenarios-only .

test-autogenerated:
	# $(CC) features test --skip-scenarios -f $(NVIM_PACKAGES) -i $(BASE_IMAGE) .
	$(CC) features test --skip-scenarios -f $(UTILS_PACKAGES) -i $(BASE_IMAGE) .

test: test-nvim test-utils test-autogenerated test-global
